// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025/2/6 18:19:28
const configMerger = require("D:/Files/Desktop/CELEHS-Data-Science-Summer-Camp/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["D:/Files/Desktop/CELEHS-Data-Science-Summer-Camp/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Files/Desktop/CELEHS-Data-Science-Summer-Camp/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Files/Desktop/CELEHS-Data-Science-Summer-Camp/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Files/Desktop/CELEHS-Data-Science-Summer-Camp/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Files/Desktop/CELEHS-Data-Science-Summer-Camp/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Files/Desktop/CELEHS-Data-Science-Summer-Camp/plugins/**/*.{js,ts,mjs}","D:/Files/Desktop/CELEHS-Data-Science-Summer-Camp/composables/**/*.{js,ts,mjs}","D:/Files/Desktop/CELEHS-Data-Science-Summer-Camp/utils/**/*.{js,ts,mjs}","D:/Files/Desktop/CELEHS-Data-Science-Summer-Camp/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/Files/Desktop/CELEHS-Data-Science-Summer-Camp/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/Files/Desktop/CELEHS-Data-Science-Summer-Camp/app.config.{js,ts,mjs}"] }));

module.exports = (() => {const cfg=config;cfg["content"]["33"] = "D:/Files/Desktop/CELEHS-Data-Science-Summer-Camp/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";cfg["darkMode"] = ["selector","[class~=\"dark\"]"];;return cfg;})()
